### ISSUE TITLE
Make metrics configurable

### ISSUE THREAD

**Issue by fl-lokalise** [lokalise/node-service-template#79]
Hello,

Today I want to have a quick discussion the `metricsPlugin`. 
The context/problem of this discussion is: Running multiple services based on `node-service-template` on one machine and omitting port conflicts. 

Right now the `metricsPlugin` is always enabled with predetermined configuration. 
-  The port is always `9080`.
-  It uses the `APP_BIND_ADDRESS` for the bind address, which seems to be intended specifically for the application.

In one of the other services, we tried an approach of enabling it for test and production environments only. While it is working, it is still a hardcoded value in a way.

So I want to discuss a proposal of adding multiple environment variables to control the `metricsPlugin`.

1. `METRICS_ENABLED` - as a more configurable option to checking the application environment. Mostly for development purposes. Make it optional and `true` by default.
2. `METRICS_BIND_ADDRESS` - this was originally mentioned by @eduard-fa. More flexibility for productions environments. Make it optional, with value of `APP_BIND_ADDRESS` by default.
3. `METRICS_PORT` - to be able to run multiple services on one machine. Mostly for development purposes. Make it optional and `9080` by default.

Questions I have: 
1. In general, do you have any comments about this proposal?
2. Should environment variables be included in `.env.default`?
3. How to approach these variable when running tests?

@kibertoad @eduard-fa

**Comment by eduard-fa** [comment]
Hey @fl-lokalise
I suggest keeping the number of variables at a minimum. All three can be substituted with just one: port can be a part of the address, and enablement can be decided based on value presence
```
METRICS_BIND_ADDRESS=0.0.0.0:8080  # Metrics are enabled
METRICS_BIND_ADDRESS=              # Metrics are disabled
```

**Comment by kibertoad** [comment]
Considering that this is an _opinionated_ template, I would argue that default should be production-friendly, which is metrics enabled on a predetermined port (9080). Any new params should be an escape hatch that can be used for the convenience of local development, but that should be an explicit override.

**Comment by fl-lokalise** [comment]
So, if I got it right @kibertoad , we should include the environment variable in the documentation, but leave it out from `.env.default`. The default should be production based and be included in the `configScope.getOptional` call. 

@eduard-fa I like the option to have just one variable, but I have 2 concerns (which I just need a green light to ignore).

1. Inconsistent variable naming and data association. 
Essential introducing 1 variables for configuration that already uses 2  (`APP_PORT` and `APP_BIND_ADDRESS` vs just `METRICS_BIND_ADDRESS`). 
We can pick another name, but it will still be 2 variables vs 1 to configure essentially the same options.

2. Post-processing will be required.
I didn't see other variables requiring post processing and I'm hesitant to add a precedent like that.


A bit off-topic, but still relevant.

In the begging I also thought that value like `METRICS_BIND_ADDRESS=` (empty) was not an option to mark the plugin as disabled, since it will fall to default.

However, given
```env
VAR1=
VAR2=
```
and performing
```ts
var1: configScope.getOptionalInteger('VAR1', 42),
var2: configScope.getOptional('VAR2', 'foo'),
```
the produced configuration had inconsistent fallback behavior
```json
{
    var1: 42,
    var2: ''
}
```

I didn't dig deep into the  `ConfigScope` class and with hopes that one of you has a quick answer. Is this intended or a bug?

**Comment by kibertoad** [comment]
> I didn't see other variables requiring post processing and I'm hesitant to add a precedent like that.

JWT tokens already do that, although in fairly crude way. ConfigScope has getOptionalTransformed method for this case, if you need it.

> I didn't dig deep into the ConfigScope class and with hopes that one of you has a quick answer. Is this intended or a bug?

I would consider that a bug, empty string should be considered an undefined value as far as configs are concerned. Could you send a PR to https://github.com/lokalise/node-core?

Using empty `METRICS_BIND_ADDRESS` for disabling metrics is very confusing, that would never be my first thought of how to disable something. And it's inconsistent with how we disable everything else (typically there is an explicit param for that, e. g. for NewRelic or BugSnag).

`env.default` ideally should have all the variables that we have. My main point is that application default (what config.ts resolves in absence of value) should be production value (metrics enabled, port 9080). `env.default` should have the overrides that make sense for local development and tests (e. g. "metrics disabled")

**Comment by fl-lokalise** [comment]
I did not have a chance to spend more time on this today. 
Will pick it up again on Monday.

**Comment by fl-lokalise** [comment]
[Created a PR](https://github.com/lokalise/node-core/pull/40) on `node-core` repo (without an actually fix though).

Going back to `metricsPlugin`. 

I'll backtrack a bit.
At this point I only really care about the ability to disable the plugin for local development to run multiple instances of `node-service-template` backed services. 
Once I can do this, I'm fine with any port that there is, and nothing else really cares about the port as well (well, tests do, and they require 9080).

So, I can start by introducing just the `METRICS_ENABLED` variable and we can add more if we actually need them.
